PYTHON_ANYWHERE = False

types = [
    # 'aho',
    # 'amibo',
    {'value': 'akari', 'name': 'Akari'},
	{'value': 'aquarium', 'name': 'Aquarium'},
	{'value': 'balanceloop', 'name': 'Balanceloop'},
	{'value': 'battleship', 'name': 'Battleship'},
	{'value': 'binairo', 'name': 'Binairo'},
	{'value': 'castlewall', 'name': 'Castlewall'},
	{'value': 'cave', 'name': 'Cave'},
	{'value': 'countryroad', 'name': 'Countryroad'},
	{'value': 'doppelblock', 'name': 'Doppelblock'},
	{'value': 'easyas', 'name': 'Easy As'},
	{'value': 'fillomino', 'name': 'Fillomino'},
	{'value': 'gokigen', 'name': 'Gokigen'},
	{'value': 'hashi', 'name': 'Hashi'},
	{'value': 'heteromino', 'name': 'Heteromino'},
	{'value': 'heyawake', 'name': 'Heyawake'},
	{'value': 'hitori', 'name': 'Hitori'},
	{'value': 'hotaru', 'name': 'Hotaru'},
	{'value': 'kakuro', 'name': 'Kakuro'},
	{'value': 'kurotto', 'name': 'Kurotto'},
	{'value': 'kuromasu', 'name': 'Kuromasu'},
	{'value': 'lits', 'name': 'LITS'},
	{'value': 'magnets', 'name': 'Magnets'},
	{'value': 'masyu', 'name': 'Masyu'},
	{'value': 'minesweeper', 'name': 'Minesweeper'},
	{'value': 'moonsun', 'name': 'Moon-or-Sun'},
	{'value': 'nagare', 'name': 'Nagare',
		'aliases': ['nagareru']},
	{'value': 'nanro', 'name': 'Nanro'},
	{'value': 'ncells', 'name': 'N Cells',
		'aliases': ['fivecells', 'fourcells']},
	{'value': 'nonogram', 'name': 'Nonogram'},
	{'value': 'norinori', 'name': 'Norinori'},
	{'value': 'numberlink', 'name': 'Numberlink'},
	{'value': 'nuribou', 'name': 'Nuribou'},
	{'value': 'nurikabe', 'name': 'Nurikabe'},
	{'value': 'nurimisaki', 'name': 'Nurimisaki'},
	{'value': 'onsen', 'name': 'Onsen'},
	{'value': 'rippleeffect', 'name': 'Ripple Effect'},
	{'value': 'shakashaka', 'name': 'Shakashaka'},
	{'value': 'shikaku', 'name': 'Shikaku'},
	{'value': 'shimaguni', 'name': 'Shimaguni',
		'aliases': ['islands']},
	{'value': 'skyscrapers', 'name': 'Skyscrapers'},
	{'value': 'slitherlink', 'name': 'Slitherlink'},
	{'value': 'spiralgalaxies', 'name': 'Spiral Galaxies'},
	{'value': 'starbattle', 'name': 'Starbattle'},
	{'value': 'statuepark', 'name': 'Statue Park'},
	{'value': 'stostone', 'name': 'Stostone'},
	{'value': 'sudoku', 'name': 'Sudoku'},
	{'value': 'tapa', 'name': 'Tapa'},
	{'value': 'tatamibari', 'name': 'Tatamibari'},
	{'value': 'tents', 'name': 'Tents'},
	{'value': 'tll', 'name': 'Tapa-Like Loop', 
		'aliases': ['tapalikeloop', 'tapa-like-loop', 'tapalike', 'tapa-like']},
	{'value': 'yajilin', 'name': 'Yajilin'},
	# 'yajilin_transparent',
	{'value': 'yajisankazusan', 'name': 'Yajisan-Kazusan',
		'aliases': ['yk', 'yajisan-kazusan', 'yajikazu']},
	{'value': 'yinyang', 'name': 'Yin-Yang'}
]
